// 内置样式块库 · D 组：结构各异的"形态"块（重点不是配色，是版式结构本身不同）。
// 进阶手法全在存活契约内：负边距叠层（大字底纹/错位色块）、border 三角（缎带/箭头/气泡尾）、
// 硬阴影贴纸（box-shadow x/y/0）、圆徽（border-radius:50%+line-height 居中）、渐变横幅、
// 拍立得（不等边内边距）、胶片孔（重复小方）。不用 flex/position/transform/SVG。
// 随主题联动令牌：{{accent}}主色 / {{tint}}浅底 / {{softTint}}更浅 / {{shade}}深字 / {{accent2}}辅助。
const B = (type, id, name, htmlTemplate) => ({ id: `form-${id}`, type, name, htmlTemplate, accentEditable: true, source: 'builtin', sourceUrl: null });
// border 三角：dir=left/right/up/down，size 高、len 长度、col 颜色
const TRI = (dir, size, len, col) => {
  const b = { left: 'border-right', right: 'border-left', up: 'border-bottom', down: 'border-top' };
  const cross = (dir === 'left' || dir === 'right') ? 'border-top:' + size + 'px solid transparent;border-bottom:' + size + 'px solid transparent;' : 'border-left:' + size + 'px solid transparent;border-right:' + size + 'px solid transparent;';
  return `<span style="display:inline-block;width:0;height:0;${cross}${b[dir]}:${len}px solid ${col};vertical-align:middle;"></span>`;
};

export const BUILTIN_BLOCKS_D = [
  // ---------------- 标题 h2：形态 ----------------
  B('h2', 't-sticker', '贴纸·硬阴影', '<section style="margin:34px 0 18px;"><span style="display:inline-block;padding:10px 20px;background-color:{{accent}};color:#ffffff;font-size:17px;font-weight:700;box-shadow:5px 5px 0 {{tint}};">{{content}}</span></section>'),
  B('h2', 't-offset-square', '错位色块', '<section style="margin:34px 0 18px;"><span style="display:inline-block;width:24px;height:24px;background-color:{{accent}};vertical-align:middle;"></span><span style="display:inline-block;vertical-align:middle;margin-left:-13px;padding:0 4px;background-color:#ffffff;font-size:19px;font-weight:800;color:{{shade}};line-height:1.4;">{{content}}</span></section>'),
  B('h2', 't-banner', '尖角横幅', '<section style="margin:30px 0 16px;text-align:center;">' + TRI('left', 18, 12, '{{accent}}') + '<span style="display:inline-block;vertical-align:middle;padding:9px 16px;background-color:{{accent}};color:#ffffff;font-size:16px;font-weight:700;letter-spacing:0.04em;">{{content}}</span>' + TRI('right', 18, 12, '{{accent}}') + '</section>'),
  B('h2', 't-ribbon-fold', '缎带·深折角', '<section style="margin:30px 0 16px;text-align:center;">' + TRI('left', 17, 11, '{{shade}}') + '<span style="display:inline-block;vertical-align:middle;padding:9px 18px;background-color:{{accent}};color:#ffffff;font-size:16px;font-weight:700;">{{content}}</span>' + TRI('right', 17, 11, '{{shade}}') + '</section>'),
  B('h2', 't-arrow-tag', '箭头标签', '<section style="margin:30px 0 16px;"><span style="display:inline-block;vertical-align:middle;padding:8px 14px;background-color:{{accent}};color:#ffffff;font-size:16px;font-weight:700;">{{content}}</span>' + TRI('right', 17, 12, '{{accent}}') + '</section>'),
  B('h2', 't-circle-badge', '圆徽标题', '<section style="margin:30px 0 16px;"><span style="display:inline-block;width:34px;height:34px;background-color:{{accent}};border-radius:50%;color:#ffffff;font-size:15px;text-align:center;line-height:34px;vertical-align:middle;">✦</span><span style="display:inline-block;vertical-align:middle;padding-left:12px;font-size:17px;font-weight:700;color:{{shade}};">{{content}}</span></section>'),
  B('h2', 't-ring-badge', '环徽标题', '<section style="margin:30px 0 16px;"><span style="display:inline-block;width:30px;height:30px;border:2px solid {{accent}};border-radius:50%;color:{{accent}};font-size:14px;text-align:center;line-height:30px;vertical-align:middle;">◆</span><span style="display:inline-block;vertical-align:middle;padding-left:12px;font-size:17px;font-weight:700;color:{{shade}};">{{content}}</span></section>'),
  B('h2', 't-bubble', '气泡标题', '<section style="margin:30px 0 18px;"><span style="display:inline-block;padding:9px 18px;background-color:{{accent}};color:#ffffff;font-size:16px;font-weight:700;border-radius:14px;">{{content}}</span><section style="margin:0 0 0 26px;">' + TRI('down', 8, 10, '{{accent}}') + '</section></section>'),
  B('h2', 't-watermark', '大字底纹', '<section style="margin:34px 0 16px;"><section style="font-size:34px;font-weight:800;color:{{tint}};line-height:0.9;letter-spacing:0.06em;">❝❝</section><section style="font-size:19px;font-weight:700;color:{{shade}};margin-top:-18px;padding-left:6px;">{{content}}</section></section>'),
  B('h2', 't-tall-bar', '粗高竖条', '<section style="margin:30px 0 16px;"><span style="display:inline-block;width:7px;height:30px;background-color:{{accent}};border-radius:4px;vertical-align:middle;margin-right:12px;"></span><span style="display:inline-block;vertical-align:middle;font-size:18px;font-weight:700;color:{{shade}};line-height:1.3;">{{content}}</span></section>'),
  B('h2', 't-frame-shadow', '描边框·硬影', '<section style="margin:32px 0 18px;"><span style="display:inline-block;padding:9px 20px;border:2px solid {{accent}};color:{{shade}};font-size:17px;font-weight:700;box-shadow:5px 5px 0 {{softTint}};">{{content}}</span></section>'),
  B('h2', 't-hero', '渐变横幅', '<section style="margin:30px 0 16px;background-image:linear-gradient(135deg,{{accent}},{{accent2}});border-radius:8px;padding:15px;text-align:center;"><span style="font-size:18px;font-weight:800;color:#ffffff;letter-spacing:0.08em;">{{content}}</span></section>'),
  B('h2', 't-hero-tint', '浅底大标', '<section style="margin:30px 0 16px;background-color:{{softTint}};border-radius:8px;padding:15px;text-align:center;"><span style="font-size:18px;font-weight:800;color:{{accent}};letter-spacing:0.06em;">{{content}}</span></section>'),
  B('h2', 't-split-cap', '色块+端帽', '<section style="margin:30px 0 16px;"><span style="display:inline-block;vertical-align:middle;padding:9px 8px 9px 16px;background-color:{{accent}};color:#ffffff;font-size:16px;font-weight:700;border-radius:6px 0 0 6px;">{{content}}</span><span style="display:inline-block;vertical-align:middle;width:0;height:0;border-top:18px solid {{accent}};border-right:12px solid transparent;"></span></section>'),
  B('h2', 't-book-spine', '书脊标题', '<section style="margin:30px 0 16px;padding:8px 14px;border-left:8px solid {{accent}};background-color:{{softTint}};"><section style="border-bottom:1px solid {{tint}};padding-bottom:6px;font-size:17px;font-weight:700;color:{{shade}};">{{content}}</section></section>'),
  B('h2', 't-underline-arrow', '箭头下划', '<section style="margin:30px 0 16px;"><span style="font-size:18px;font-weight:700;color:{{shade}};">{{content}}</span><section style="margin-top:8px;"><span style="display:inline-block;width:54px;height:2px;background-color:{{accent}};vertical-align:middle;"></span>' + TRI('right', 5, 6, '{{accent}}') + '</section></section>'),
  B('h2', 't-big-quote', '巨引号标题', '<section style="margin:30px 0 16px;"><span style="color:{{accent}};font-size:36px;font-weight:800;line-height:0.1;vertical-align:-16px;">“</span><span style="font-size:18px;font-weight:700;color:{{shade}};padding-left:8px;vertical-align:middle;">{{content}}</span></section>'),
  B('h2', 't-double-tag', '双拼标签', '<section style="margin:30px 0 16px;"><span style="display:inline-block;vertical-align:middle;padding:6px 10px;background-color:{{accent}};color:#ffffff;font-size:13px;font-weight:700;border-radius:4px 0 0 4px;">专题</span><span style="display:inline-block;vertical-align:middle;padding:6px 14px;background-color:{{tint}};color:{{shade}};font-size:16px;font-weight:700;border-radius:0 4px 4px 0;">{{content}}</span></section>'),

  // ---------------- 引用/提示框 quote：形态 ----------------
  B('quote', 'c-callout', '提示框', '<section style="margin:20px 0;padding:14px 16px;background-color:{{softTint}};border-left:4px solid {{accent}};border-radius:0 6px 6px 0;"><span style="display:inline-block;padding:2px 9px;background-color:{{accent}};color:#ffffff;font-size:12px;font-weight:700;border-radius:3px;margin-bottom:8px;">提 示</span><br><span style="font-size:15px;color:{{shade}};line-height:1.85;">{{content}}</span></section>'),
  B('quote', 'c-bubble', '气泡引用', '<section style="margin:20px 0;"><section style="padding:14px 16px;background-color:{{tint}};border-radius:12px;"><span style="font-size:15px;color:{{shade}};line-height:1.9;">{{content}}</span></section><section style="margin:0 0 0 26px;">' + TRI('down', 9, 11, '{{tint}}') + '</section></section>'),
  B('quote', 'c-sticky', '便签·硬阴影', '<section style="margin:22px 0;"><section style="padding:15px 17px;background-color:{{tint}};box-shadow:6px 6px 0 {{softTint}};"><span style="font-size:15px;color:{{shade}};line-height:1.9;">{{content}}</span></section></section>'),
  B('quote', 'c-topbar', '色顶投影卡', '<section style="margin:20px 0;background-color:#ffffff;border-top:4px solid {{accent}};border-radius:0 0 8px 8px;box-shadow:0 5px 16px rgba(0,0,0,0.08);padding:15px 17px;"><span style="font-size:15px;color:{{shade}};line-height:1.9;">{{content}}</span></section>'),
  B('quote', 'c-big-mark', '巨引号背景', '<section style="margin:22px 0;"><section style="font-size:44px;font-weight:800;color:{{tint}};line-height:0.5;">“</section><section style="margin-top:-6px;padding-left:10px;font-size:15px;color:{{shade}};line-height:1.9;">{{content}}</section></section>'),
  B('quote', 'c-corner', '双角引号', '<section style="margin:22px 0;padding:6px 20px;"><section style="color:{{accent}};font-size:20px;font-weight:700;line-height:0.6;">「</section><section style="padding:4px 8px;font-size:15px;color:{{shade}};line-height:1.9;">{{content}}</section><section style="color:{{accent}};font-size:20px;font-weight:700;text-align:right;line-height:0.4;">」</section></section>'),
  B('quote', 'c-tab', '标签页引用', '<section style="margin:22px 0;"><span style="display:inline-block;padding:5px 16px;background-color:{{accent}};color:#ffffff;font-size:13px;font-weight:700;border-radius:6px 6px 0 0;">语 录</span><section style="padding:14px 16px;background-color:{{softTint}};border-radius:0 8px 8px 8px;"><span style="font-size:15px;color:{{shade}};line-height:1.9;">{{content}}</span></section></section>'),

  // ---------------- 分割线 divider：形态 ----------------
  B('divider', 'v-arrow', '箭头分割', '<section style="margin:22px 0;text-align:center;"><span style="display:inline-block;width:32%;height:1px;background-color:{{accent}};vertical-align:middle;"></span><span style="display:inline-block;vertical-align:middle;padding:0 4px;">' + TRI('right', 5, 6, '{{accent}}') + '</span><span style="display:inline-block;width:32%;height:1px;background-color:{{accent}};vertical-align:middle;"></span></section>'),
  B('divider', 'v-banner', '横幅分割', '<section style="margin:20px 0;text-align:center;"><span style="display:inline-block;width:30%;height:1px;background-color:{{accent}};vertical-align:middle;"></span><span style="display:inline-block;vertical-align:middle;padding:3px 14px;margin:0 8px;background-color:{{accent}};color:#ffffff;font-size:11px;border-radius:10px;">✦</span><span style="display:inline-block;width:30%;height:1px;background-color:{{accent}};vertical-align:middle;"></span></section>'),
  B('divider', 'v-grow', '渐变点阵', '<section style="margin:20px 0;text-align:center;"><span style="display:inline-block;width:3px;height:3px;border-radius:50%;background-color:{{accent}};vertical-align:middle;margin:0 3px;"></span><span style="display:inline-block;width:5px;height:5px;border-radius:50%;background-color:{{accent}};vertical-align:middle;margin:0 3px;"></span><span style="display:inline-block;width:8px;height:8px;border-radius:50%;background-color:{{accent}};vertical-align:middle;margin:0 4px;"></span><span style="display:inline-block;width:5px;height:5px;border-radius:50%;background-color:{{accent}};vertical-align:middle;margin:0 3px;"></span><span style="display:inline-block;width:3px;height:3px;border-radius:50%;background-color:{{accent}};vertical-align:middle;margin:0 3px;"></span></section>'),
  B('divider', 'v-stack', '粗细叠线', '<section style="margin:22px 0;"><section style="width:70px;height:4px;border-radius:99px;background-color:{{accent}};margin:0 auto;"></section><section style="height:1px;background-color:{{tint}};margin-top:-2px;"></section></section>'),
  B('divider', 'v-bracket', '括号分割', '<section style="margin:22px 0;text-align:center;"><span style="color:{{accent}};font-size:18px;vertical-align:middle;">【</span><span style="display:inline-block;width:40%;height:1px;background-color:{{accent}};vertical-align:middle;margin:0 4px;"></span><span style="color:{{accent}};font-size:18px;vertical-align:middle;">】</span></section>'),

  // ---------------- 图片框 imageCard：形态 ----------------
  B('imageCard', 'p-polaroid', '拍立得', '<section style="margin:20px 0;text-align:center;"><section style="display:inline-block;max-width:100%;background-color:#ffffff;padding:9px 9px 0;box-shadow:0 5px 16px rgba(0,0,0,0.16);"><img src="{{src}}" style="display:block;width:100%;max-width:100%;"><section style="padding:11px 4px 13px;font-size:13px;color:{{shade}};">{{#caption}}{{caption}}{{/caption}}</section></section></section>'),
  B('imageCard', 'p-offset', '错位色影图', '<section style="margin:20px 0;text-align:center;"><img src="{{src}}" style="display:inline-block;width:96%;max-width:96%;box-shadow:9px 9px 0 {{accent}};">{{#caption}}<section style="margin-top:12px;font-size:13px;color:{{shade}};">{{caption}}</section>{{/caption}}</section>'),
  B('imageCard', 'p-film', '胶片孔图', '<section style="margin:20px 0;background-color:{{shade}};padding:10px 8px;"><section style="text-align:center;line-height:0;margin-bottom:6px;"><span style="display:inline-block;width:10px;height:6px;background-color:{{softTint}};border-radius:1px;margin:0 4px;"></span><span style="display:inline-block;width:10px;height:6px;background-color:{{softTint}};border-radius:1px;margin:0 4px;"></span><span style="display:inline-block;width:10px;height:6px;background-color:{{softTint}};border-radius:1px;margin:0 4px;"></span><span style="display:inline-block;width:10px;height:6px;background-color:{{softTint}};border-radius:1px;margin:0 4px;"></span><span style="display:inline-block;width:10px;height:6px;background-color:{{softTint}};border-radius:1px;margin:0 4px;"></span></section><img src="{{src}}" style="display:block;width:100%;max-width:100%;"><section style="text-align:center;line-height:0;margin-top:6px;"><span style="display:inline-block;width:10px;height:6px;background-color:{{softTint}};border-radius:1px;margin:0 4px;"></span><span style="display:inline-block;width:10px;height:6px;background-color:{{softTint}};border-radius:1px;margin:0 4px;"></span><span style="display:inline-block;width:10px;height:6px;background-color:{{softTint}};border-radius:1px;margin:0 4px;"></span><span style="display:inline-block;width:10px;height:6px;background-color:{{softTint}};border-radius:1px;margin:0 4px;"></span><span style="display:inline-block;width:10px;height:6px;background-color:{{softTint}};border-radius:1px;margin:0 4px;"></span></section>{{#caption}}<section style="margin-top:8px;font-size:12px;color:#ffffff;text-align:center;">{{caption}}</section>{{/caption}}</section>'),
];
