// 内置样式块库 · C 组：手工精调的"精品原创"样式块（非组合生成，每个单独设计调校）。
// 设计语言取自逆向秀米学到的排版规律（圆头细线 height+border-radius:99px、三段式 line—text—line 用
// inline-block+vertical-align 不使用 flex、协调调色板 主色/浅底/深字/辅助色、符号点缀、疏排字距），
// 但每个都是原创组合，不搬秀米任何具体模板。全部随主题色联动（用 {{accent}}=主色 / {{tint}} 浅底 /
// {{softTint}} 更浅 / {{shade}} 深字 / {{accent2}} 辅助色 令牌，applyBlock 由 accent 派生调色板替换）。
// 存活契约：仅内联 style；display 只用 block|inline-block（禁 flex/grid）；禁 position/transform/
// font-family/class=/id=；线条用 height+background 或 border 实现。id 前缀 premium- 防与 A/B 撞名。

const B = (type, id, name, htmlTemplate) => ({ id: `premium-${id}`, type, name, htmlTemplate, accentEditable: true, source: 'builtin', sourceUrl: null });

// 复用片段
const RBAR = (w, col) => `<section style="width:${w};height:3px;border-radius:99px;background-color:${col};margin-top:9px;"></section>`;

export const BUILTIN_BLOCKS_C = [
  // ============================ 标题 h2（24）============================
  B('h2', 'h2-left-bar', '左竖线·极简', '<section style="margin:32px 0 16px;padding:1px 0 1px 13px;border-left:4px solid {{accent}};"><span style="font-size:18px;font-weight:700;color:{{shade}};line-height:1.5;letter-spacing:0.02em;">{{content}}</span></section>'),
  B('h2', 'h2-left-soft', '左粗条·浅底', '<section style="margin:30px 0 16px;padding:9px 16px 9px 14px;border-left:5px solid {{accent}};background-color:{{softTint}};border-radius:0 6px 6px 0;"><span style="font-size:18px;font-weight:700;color:{{shade}};line-height:1.5;">{{content}}</span></section>'),
  B('h2', 'h2-left-dot', '左圆点·清爽', '<section style="margin:30px 0 16px;"><span style="display:inline-block;width:9px;height:9px;border-radius:50%;background-color:{{accent}};vertical-align:middle;margin-right:10px;"></span><span style="font-size:18px;font-weight:700;color:{{shade}};vertical-align:middle;">{{content}}</span></section>'),
  B('h2', 'h2-underline-round', '圆头下划·左', '<section style="margin:30px 0 16px;"><span style="font-size:19px;font-weight:700;color:{{shade}};line-height:1.5;">{{content}}</span>' + RBAR('48px', '{{accent}}') + '</section>'),
  B('h2', 'h2-underline-center', '圆头下划·中', '<section style="margin:30px 0 16px;text-align:center;"><span style="font-size:19px;font-weight:700;color:{{shade}};line-height:1.5;">{{content}}</span><section style="width:48px;height:3px;border-radius:99px;background-color:{{accent}};margin:9px auto 0;"></section></section>'),
  B('h2', 'h2-underline-tight', '贴字下划', '<section style="margin:30px 0 16px;"><span style="display:inline-block;font-size:18px;font-weight:700;color:{{shade}};line-height:1.6;border-bottom:3px solid {{accent}};padding-bottom:4px;">{{content}}</span></section>'),
  B('h2', 'h2-underline-fade', '渐隐下划', '<section style="margin:30px 0 16px;"><span style="font-size:18px;font-weight:700;color:{{shade}};line-height:1.5;">{{content}}</span><section style="height:2px;background-image:linear-gradient(90deg,{{accent}},#ffffff);margin-top:9px;"></section></section>'),
  B('h2', 'h2-underline-duo', '双色下划', '<section style="margin:30px 0 16px;"><span style="font-size:18px;font-weight:700;color:{{shade}};line-height:1.5;">{{content}}</span><section style="margin-top:9px;"><span style="display:inline-block;width:32px;height:3px;border-radius:99px;background-color:{{accent}};vertical-align:middle;"></span><span style="display:inline-block;width:14px;height:3px;border-radius:99px;background-color:{{accent2}};vertical-align:middle;margin-left:5px;"></span></section></section>'),
  B('h2', 'h2-fill-solid', '主色块·方角', '<section style="margin:30px 0 16px;"><span style="display:inline-block;padding:9px 20px;background-color:{{accent}};border-radius:3px;font-size:16px;font-weight:700;color:#ffffff;letter-spacing:0.05em;line-height:1.5;">{{content}}</span></section>'),
  B('h2', 'h2-fill-pill', '主色胶囊', '<section style="margin:30px 0 16px;text-align:center;"><span style="display:inline-block;padding:8px 24px;background-color:{{accent}};border-radius:22px;font-size:16px;font-weight:700;color:#ffffff;letter-spacing:0.06em;">{{content}}</span></section>'),
  B('h2', 'h2-fill-grad', '双色渐变块', '<section style="margin:30px 0 16px;"><span style="display:inline-block;padding:9px 22px;background-image:linear-gradient(135deg,{{accent}},{{accent2}});border-radius:8px;font-size:16px;font-weight:700;color:#ffffff;letter-spacing:0.04em;">{{content}}</span></section>'),
  B('h2', 'h2-fill-tint', '浅底深字块', '<section style="margin:30px 0 16px;"><span style="display:inline-block;padding:9px 20px;background-color:{{tint}};border-radius:6px;font-size:16px;font-weight:700;color:{{shade}};letter-spacing:0.04em;">{{content}}</span></section>'),
  B('h2', 'h2-fill-border', '描边浅底块', '<section style="margin:30px 0 16px;text-align:center;"><span style="display:inline-block;padding:8px 22px;background-color:{{softTint}};border:1px solid {{accent}};border-radius:6px;font-size:16px;font-weight:700;color:{{shade}};">{{content}}</span></section>'),
  B('h2', 'h2-rule-updown', '上下双线·疏排', '<section style="margin:30px 0 16px;text-align:center;padding:10px 0;border-top:1px solid {{accent}};border-bottom:1px solid {{accent}};"><span style="font-size:17px;font-weight:700;color:{{shade}};letter-spacing:0.15em;">{{content}}</span></section>'),
  B('h2', 'h2-rule-thick', '上下粗线·居中', '<section style="margin:30px 0 16px;text-align:center;padding:9px 0;border-top:3px solid {{accent}};border-bottom:1px solid {{accent}};"><span style="font-size:17px;font-weight:700;color:{{shade}};letter-spacing:0.08em;">{{content}}</span></section>'),
  B('h2', 'h2-box', '细边框·浅底', '<section style="margin:30px 0 16px;text-align:center;"><span style="display:inline-block;padding:9px 22px;border:1px solid {{accent}};border-radius:4px;background-color:{{softTint}};font-size:16px;font-weight:700;color:{{shade}};">{{content}}</span></section>'),
  B('h2', 'h2-frame-double', '双层描边框', '<section style="margin:30px 0 16px;text-align:center;padding:3px;border:1px solid {{accent}};border-radius:6px;"><section style="padding:8px 0;border:1px solid {{tint}};border-radius:4px;"><span style="font-size:16px;font-weight:700;color:{{shade}};letter-spacing:0.06em;">{{content}}</span></section></section>'),
  B('h2', 'h2-seg', '三段线·居中', '<section style="margin:30px 0 16px;text-align:center;"><span style="display:inline-block;width:18%;height:1px;background-color:{{accent}};vertical-align:middle;"></span><span style="display:inline-block;padding:0 14px;font-size:17px;font-weight:700;color:{{shade}};vertical-align:middle;letter-spacing:0.04em;">{{content}}</span><span style="display:inline-block;width:18%;height:1px;background-color:{{accent}};vertical-align:middle;"></span></section>'),
  B('h2', 'h2-seg-diamond', '三段线·菱点', '<section style="margin:30px 0 16px;text-align:center;"><span style="display:inline-block;width:15%;height:1px;background-color:{{accent}};vertical-align:middle;"></span><span style="color:{{accent}};font-size:10px;vertical-align:middle;margin:0 7px;">◆</span><span style="display:inline-block;padding:0 8px;font-size:17px;font-weight:700;color:{{shade}};vertical-align:middle;">{{content}}</span><span style="color:{{accent}};font-size:10px;vertical-align:middle;margin:0 7px;">◆</span><span style="display:inline-block;width:15%;height:1px;background-color:{{accent}};vertical-align:middle;"></span></section>'),
  B('h2', 'h2-sym-wrap', '符号包裹·星', '<section style="margin:30px 0 16px;text-align:center;"><span style="color:{{accent}};font-size:14px;vertical-align:middle;">✦</span><span style="font-size:17px;font-weight:700;color:{{shade}};padding:0 12px;vertical-align:middle;letter-spacing:0.04em;">{{content}}</span><span style="color:{{accent}};font-size:14px;vertical-align:middle;">✦</span></section>'),
  B('h2', 'h2-chip-prefix', '色签前缀', '<section style="margin:30px 0 16px;"><span style="display:inline-block;width:20px;height:20px;background-color:{{accent}};border-radius:5px;vertical-align:middle;margin-right:10px;"></span><span style="font-size:18px;font-weight:700;color:{{shade}};vertical-align:middle;">{{content}}</span></section>'),
  B('h2', 'h2-num-badge', '编号感·菱徽', '<section style="margin:30px 0 16px;"><span style="display:inline-block;font-size:23px;color:{{accent}};vertical-align:middle;line-height:1;">❖</span><span style="display:inline-block;font-size:17px;font-weight:700;color:{{shade}};vertical-align:middle;padding-left:11px;margin-left:11px;border-left:2px solid {{accent}};line-height:1.3;">{{content}}</span></section>'),
  B('h2', 'h2-bracket', '书名号强调', '<section style="margin:30px 0 16px;"><span style="font-size:20px;font-weight:700;color:{{accent}};vertical-align:middle;">「</span><span style="font-size:18px;font-weight:700;color:{{shade}};vertical-align:middle;padding:0 2px;">{{content}}</span><span style="font-size:20px;font-weight:700;color:{{accent}};vertical-align:middle;">」</span></section>'),
  B('h2', 'h2-plain-spaced', '大字疏排·极简', '<section style="margin:32px 0 16px;text-align:center;"><span style="font-size:20px;font-weight:800;color:{{accent}};letter-spacing:0.22em;">{{content}}</span></section>'),

  // ============================ 小标题 h3（14）============================
  B('h3', 'h3-dot', '圆点小标', '<section style="margin:22px 0 12px;"><span style="display:inline-block;width:7px;height:7px;border-radius:50%;background-color:{{accent}};vertical-align:middle;margin-right:8px;"></span><span style="font-size:16px;font-weight:600;color:{{shade}};vertical-align:middle;">{{content}}</span></section>'),
  B('h3', 'h3-bar', '竖条小标', '<section style="margin:22px 0 12px;"><span style="display:inline-block;width:4px;height:15px;border-radius:2px;background-color:{{accent}};vertical-align:-2px;margin-right:9px;"></span><span style="font-size:16px;font-weight:600;color:{{shade}};">{{content}}</span></section>'),
  B('h3', 'h3-square', '方块小标', '<section style="margin:22px 0 12px;"><span style="display:inline-block;width:9px;height:9px;background-color:{{accent}};vertical-align:middle;margin-right:9px;"></span><span style="font-size:16px;font-weight:600;color:{{shade}};vertical-align:middle;">{{content}}</span></section>'),
  B('h3', 'h3-tri', '三角小标', '<section style="margin:22px 0 12px;"><span style="color:{{accent}};font-size:12px;vertical-align:middle;margin-right:8px;">▶</span><span style="font-size:16px;font-weight:600;color:{{shade}};vertical-align:middle;">{{content}}</span></section>'),
  B('h3', 'h3-tag-solid', '主色小签', '<section style="margin:22px 0 12px;"><span style="display:inline-block;padding:4px 13px;background-color:{{accent}};border-radius:4px;font-size:14px;font-weight:600;color:#ffffff;">{{content}}</span></section>'),
  B('h3', 'h3-tag-pill', '主色小胶囊', '<section style="margin:22px 0 12px;"><span style="display:inline-block;padding:4px 14px;background-color:{{accent}};border-radius:14px;font-size:14px;font-weight:600;color:#ffffff;">{{content}}</span></section>'),
  B('h3', 'h3-tag-tint', '浅底小签', '<section style="margin:22px 0 12px;"><span style="display:inline-block;padding:4px 13px;background-color:{{tint}};border-radius:4px;font-size:14px;font-weight:600;color:{{shade}};">{{content}}</span></section>'),
  B('h3', 'h3-underline', '短线小标', '<section style="margin:22px 0 12px;"><span style="font-size:16px;font-weight:600;color:{{shade}};border-bottom:2px solid {{accent}};padding-bottom:3px;">{{content}}</span></section>'),
  B('h3', 'h3-bracket', '直角括号小标', '<section style="margin:22px 0 12px;"><span style="font-size:16px;font-weight:600;color:{{accent}};">「</span><span style="font-size:16px;font-weight:600;color:{{shade}};">{{content}}</span><span style="font-size:16px;font-weight:600;color:{{accent}};">」</span></section>'),
  B('h3', 'h3-num', '角标编号小标', '<section style="margin:22px 0 12px;"><span style="display:inline-block;padding:1px 8px;background-color:{{accent}};border-radius:3px;font-size:13px;font-weight:700;color:#ffffff;vertical-align:middle;margin-right:9px;">0</span><span style="font-size:16px;font-weight:600;color:{{shade}};vertical-align:middle;">{{content}}</span></section>'),
  B('h3', 'h3-star', '星标小标', '<section style="margin:22px 0 12px;"><span style="color:{{accent}};font-size:13px;vertical-align:middle;margin-right:8px;">✦</span><span style="font-size:16px;font-weight:600;color:{{shade}};vertical-align:middle;">{{content}}</span></section>'),
  B('h3', 'h3-line-prefix', '细线前缀小标', '<section style="margin:22px 0 12px;"><span style="display:inline-block;width:18px;height:2px;background-color:{{accent}};vertical-align:middle;margin-right:10px;"></span><span style="font-size:16px;font-weight:600;color:{{shade}};vertical-align:middle;letter-spacing:0.04em;">{{content}}</span></section>'),
  B('h3', 'h3-plain', '纯色疏排小标', '<section style="margin:20px 0 10px;"><span style="font-size:15px;font-weight:600;color:{{accent}};letter-spacing:0.1em;">{{content}}</span></section>'),
  B('h3', 'h3-double-dot', '双点小标', '<section style="margin:22px 0 12px;"><span style="color:{{accent}};font-size:14px;vertical-align:middle;margin-right:8px;">••</span><span style="font-size:16px;font-weight:600;color:{{shade}};vertical-align:middle;">{{content}}</span></section>'),

  // ============================ 引用 quote（14）============================
  B('quote', 'q-left-soft', '左条·浅底', '<section style="margin:20px 0;padding:13px 16px;border-left:3px solid {{accent}};background-color:{{softTint}};border-radius:0 6px 6px 0;"><span style="font-size:15px;color:{{shade}};line-height:1.9;">{{content}}</span></section>'),
  B('quote', 'q-left-plain', '左条·无底', '<section style="margin:20px 0;padding:4px 0 4px 15px;border-left:3px solid {{accent}};"><span style="font-size:15px;color:{{shade}};line-height:1.9;">{{content}}</span></section>'),
  B('quote', 'q-left-tint', '左条·色底', '<section style="margin:20px 0;padding:14px 16px;border-left:4px solid {{accent}};background-color:{{tint}};border-radius:0 8px 8px 0;"><span style="font-size:15px;color:{{shade}};line-height:1.9;">{{content}}</span></section>'),
  B('quote', 'q-mark', '弯引号', '<section style="margin:20px 0;padding:6px 14px;"><span style="color:{{accent}};font-size:30px;font-weight:800;line-height:0.1;vertical-align:-14px;">“</span><span style="font-size:15px;color:{{shade}};line-height:1.9;padding-left:6px;">{{content}}</span></section>'),
  B('quote', 'q-mark-center', '弯引号·居中', '<section style="margin:20px 0;text-align:center;padding:8px 16px;"><section style="color:{{accent}};font-size:26px;font-weight:800;line-height:1;">“</section><span style="font-size:15px;color:{{shade}};line-height:1.9;">{{content}}</span></section>'),
  B('quote', 'q-rule', '上下线引用', '<section style="margin:20px 0;padding:12px 16px;border-top:2px solid {{accent}};border-bottom:2px solid {{accent}};"><span style="font-size:15px;color:{{shade}};line-height:1.9;">{{content}}</span></section>'),
  B('quote', 'q-card-soft', '卡片·浅底投影', '<section style="margin:20px 0;padding:16px 18px;background-color:{{softTint}};border-radius:10px;box-shadow:0 4px 14px rgba(0,0,0,0.06);"><span style="font-size:15px;color:{{shade}};line-height:1.9;">{{content}}</span></section>'),
  B('quote', 'q-card-tint', '卡片·色底', '<section style="margin:20px 0;padding:16px 18px;background-color:{{tint}};border-radius:10px;"><span style="font-size:15px;color:{{shade}};line-height:1.9;">{{content}}</span></section>'),
  B('quote', 'q-corner', '色顶卡片', '<section style="margin:20px 0;padding:14px 18px;background-color:{{softTint}};border-top:3px solid {{accent}};border-radius:0 0 8px 8px;"><span style="font-size:15px;color:{{shade}};line-height:1.9;">{{content}}</span></section>'),
  B('quote', 'q-thin-top', '细线起头', '<section style="margin:20px 0;padding:8px 16px;"><section style="width:30px;height:2px;background-color:{{accent}};margin-bottom:10px;"></section><span style="font-size:15px;color:{{shade}};line-height:1.9;">{{content}}</span></section>'),
  B('quote', 'q-dashed', '虚框引用', '<section style="margin:20px 0;padding:14px 16px;border:1px dashed {{accent}};border-radius:6px;background-color:{{softTint}};"><span style="font-size:15px;color:{{shade}};line-height:1.9;">{{content}}</span></section>'),
  B('quote', 'q-double-left', '双竖条引用', '<section style="margin:20px 0;padding:4px 0 4px 16px;border-left:6px double {{accent}};"><span style="font-size:15px;color:{{shade}};line-height:1.9;">{{content}}</span></section>'),
  B('quote', 'q-badge', '标签引用', '<section style="margin:20px 0;padding:16px 16px 14px;background-color:{{softTint}};border-radius:8px;"><span style="display:inline-block;padding:2px 10px;background-color:{{accent}};border-radius:3px;font-size:12px;color:#ffffff;margin-bottom:9px;">摘 要</span><br><span style="font-size:15px;color:{{shade}};line-height:1.9;">{{content}}</span></section>'),
  B('quote', 'q-center-plain', '居中语录', '<section style="margin:20px 0;text-align:center;padding:10px 18px;"><span style="font-size:15px;color:{{shade}};line-height:2;letter-spacing:0.02em;">{{content}}</span></section>'),

  // ============================ 分割线 divider（18）============================
  B('divider', 'd-round', '圆头细线', '<section style="margin:22px 0;text-align:center;"><section style="display:inline-block;width:60%;height:3px;border-radius:99px;background-color:{{accent}};vertical-align:middle;"></section></section>'),
  B('divider', 'd-thin', '单细线', '<section style="margin:22px 0;text-align:center;"><section style="display:inline-block;width:100%;height:1px;background-color:{{accent}};vertical-align:middle;"></section></section>'),
  B('divider', 'd-grad', '中浓渐变线', '<section style="margin:22px 0;height:2px;background-image:linear-gradient(90deg,#ffffff,{{accent}},#ffffff);"></section>'),
  B('divider', 'd-dashed', '虚线', '<section style="margin:22px 0;border-top:1px dashed {{accent}};"></section>'),
  B('divider', 'd-dotted', '点线', '<section style="margin:22px 0;border-top:2px dotted {{accent}};"></section>'),
  B('divider', 'd-double', '双实线', '<section style="margin:22px 0;border-top:3px double {{accent}};"></section>'),
  B('divider', 'd-sym-diamond', '菱形分割', '<section style="margin:22px 0;text-align:center;"><span style="display:inline-block;width:34%;height:1px;background-color:{{accent}};vertical-align:middle;"></span><span style="color:{{accent}};font-size:12px;vertical-align:middle;padding:0 12px;">◆</span><span style="display:inline-block;width:34%;height:1px;background-color:{{accent}};vertical-align:middle;"></span></section>'),
  B('divider', 'd-sym-star', '星形分割', '<section style="margin:22px 0;text-align:center;"><span style="display:inline-block;width:34%;height:1px;background-color:{{accent}};vertical-align:middle;"></span><span style="color:{{accent}};font-size:13px;vertical-align:middle;padding:0 12px;">✦</span><span style="display:inline-block;width:34%;height:1px;background-color:{{accent}};vertical-align:middle;"></span></section>'),
  B('divider', 'd-sym-flower', '花形分割', '<section style="margin:22px 0;text-align:center;"><span style="display:inline-block;width:34%;height:1px;background-color:{{accent}};vertical-align:middle;"></span><span style="color:{{accent}};font-size:13px;vertical-align:middle;padding:0 12px;">❋</span><span style="display:inline-block;width:34%;height:1px;background-color:{{accent}};vertical-align:middle;"></span></section>'),
  B('divider', 'd-sym-dot', '圆点分割', '<section style="margin:22px 0;text-align:center;"><span style="display:inline-block;width:34%;height:1px;background-color:{{accent}};vertical-align:middle;"></span><span style="display:inline-block;width:6px;height:6px;border-radius:50%;background-color:{{accent}};vertical-align:middle;margin:0 12px;"></span><span style="display:inline-block;width:34%;height:1px;background-color:{{accent}};vertical-align:middle;"></span></section>'),
  B('divider', 'd-sym-ring', '环点分割', '<section style="margin:22px 0;text-align:center;"><span style="display:inline-block;width:34%;height:1px;background-color:{{accent}};vertical-align:middle;"></span><span style="display:inline-block;width:8px;height:8px;border-radius:50%;border:2px solid {{accent}};vertical-align:middle;margin:0 12px;"></span><span style="display:inline-block;width:34%;height:1px;background-color:{{accent}};vertical-align:middle;"></span></section>'),
  B('divider', 'd-three-dot', '三点', '<section style="margin:20px 0;text-align:center;color:{{accent}};font-size:16px;letter-spacing:0.4em;">•••</section>'),
  B('divider', 'd-three-star', '三星', '<section style="margin:20px 0;text-align:center;color:{{accent}};font-size:13px;letter-spacing:0.5em;">✦✦✦</section>'),
  B('divider', 'd-wave', '波浪', '<section style="margin:20px 0;text-align:center;color:{{accent}};font-size:15px;letter-spacing:0.15em;">〰〰〰</section>'),
  B('divider', 'd-short-round', '短圆头', '<section style="margin:22px 0;text-align:center;"><section style="display:inline-block;width:44px;height:4px;border-radius:99px;background-color:{{accent}};vertical-align:middle;"></section></section>'),
  B('divider', 'd-duo', '双色短线', '<section style="margin:22px 0;text-align:center;"><span style="display:inline-block;width:36px;height:3px;border-radius:99px;background-color:{{accent}};vertical-align:middle;"></span><span style="display:inline-block;width:16px;height:3px;border-radius:99px;background-color:{{accent2}};vertical-align:middle;margin-left:6px;"></span></section>'),
  B('divider', 'd-dot-row', '细点排', '<section style="margin:20px 0;text-align:center;color:{{accent}};font-size:9px;letter-spacing:0.5em;">••••••••••</section>'),
  B('divider', 'd-bracket', '括号分割', '<section style="margin:20px 0;text-align:center;color:{{accent}};font-size:15px;letter-spacing:0.2em;">— ✦ —</section>'),

  // ============================ 落款/引导 signoff（8）============================
  B('signoff', 's-end', '落款·疏排主色', '<section style="margin:26px 0 12px;text-align:center;color:{{accent}};font-size:14px;letter-spacing:0.25em;">{{content}}</section>'),
  B('signoff', 's-end-dot', '落款·深字', '<section style="margin:26px 0 12px;text-align:center;color:{{shade}};font-size:14px;letter-spacing:0.2em;">{{content}}</section>'),
  B('signoff', 's-flower', '落款·花饰', '<section style="margin:26px 0 12px;text-align:center;"><section style="color:{{accent}};font-size:14px;margin-bottom:6px;">❉</section><span style="color:{{shade}};font-size:13px;letter-spacing:0.2em;">{{content}}</span></section>'),
  B('signoff', 's-line', '落款·细线夹', '<section style="margin:26px 0 12px;text-align:center;"><span style="display:inline-block;width:26px;height:1px;background-color:{{accent}};vertical-align:middle;"></span><span style="color:{{shade}};font-size:13px;padding:0 12px;vertical-align:middle;letter-spacing:0.15em;">{{content}}</span><span style="display:inline-block;width:26px;height:1px;background-color:{{accent}};vertical-align:middle;"></span></section>'),
  B('signoff', 's-follow-solid', '落款·主色胶囊', '<section style="margin:24px 0;text-align:center;"><span style="display:inline-block;padding:8px 24px;background-color:{{accent}};border-radius:22px;font-size:14px;font-weight:600;color:#ffffff;letter-spacing:0.03em;">{{content}}</span></section>'),
  B('signoff', 's-follow-tint', '落款·浅底胶囊', '<section style="margin:24px 0;text-align:center;"><span style="display:inline-block;padding:8px 24px;background-color:{{tint}};border-radius:22px;font-size:14px;font-weight:600;color:{{shade}};">{{content}}</span></section>'),
  B('signoff', 's-follow-dashed', '落款·虚框', '<section style="margin:24px 0;text-align:center;"><span style="display:inline-block;padding:8px 22px;background-color:{{softTint}};border:1px dashed {{accent}};border-radius:8px;font-size:14px;font-weight:600;color:{{shade}};">{{content}}</span></section>'),
  B('signoff', 's-badge', '落款·上箭头', '<section style="margin:24px 0;text-align:center;"><section style="color:{{accent}};font-size:16px;line-height:1;margin-bottom:4px;">▲</section><span style="font-size:13px;color:{{shade}};letter-spacing:0.05em;">{{content}}</span></section>'),

  // ============================ 图片框 imageCard（8）============================
  B('imageCard', 'i-thin', '细边框图', '<section style="margin:18px 0;text-align:center;"><section style="display:inline-block;max-width:100%;border:1px solid {{accent}};padding:5px;border-radius:2px;"><img src="{{src}}" style="display:block;width:100%;max-width:100%;"></section>{{#caption}}<section style="margin-top:8px;font-size:13px;color:{{shade}};">{{caption}}</section>{{/caption}}</section>'),
  B('imageCard', 'i-thick', '粗边框图', '<section style="margin:18px 0;text-align:center;"><section style="display:inline-block;max-width:100%;border:3px solid {{accent}};"><img src="{{src}}" style="display:block;width:100%;max-width:100%;"></section>{{#caption}}<section style="margin-top:8px;font-size:13px;color:{{shade}};">{{caption}}</section>{{/caption}}</section>'),
  B('imageCard', 'i-mat', '衬底相框', '<section style="margin:18px 0;text-align:center;"><section style="display:inline-block;max-width:100%;background-color:{{softTint}};padding:8px;border-radius:4px;"><img src="{{src}}" style="display:block;width:100%;max-width:100%;border-radius:2px;"></section>{{#caption}}<section style="margin-top:8px;font-size:13px;color:{{shade}};">{{caption}}</section>{{/caption}}</section>'),
  B('imageCard', 'i-shadow', '投影图', '<section style="margin:18px 0;text-align:center;"><img src="{{src}}" style="display:inline-block;width:100%;max-width:100%;border-radius:6px;box-shadow:0 6px 18px rgba(0,0,0,0.16);">{{#caption}}<section style="margin-top:10px;font-size:13px;color:{{shade}};">{{caption}}</section>{{/caption}}</section>'),
  B('imageCard', 'i-round', '圆角图', '<section style="margin:18px 0;text-align:center;"><img src="{{src}}" style="display:inline-block;width:100%;max-width:100%;border-radius:12px;">{{#caption}}<section style="margin-top:8px;font-size:13px;color:{{shade}};">{{caption}}</section>{{/caption}}</section>'),
  B('imageCard', 'i-cap-bar', '色条图注', '<section style="margin:18px 0;"><img src="{{src}}" style="display:block;width:100%;max-width:100%;">{{#caption}}<section style="padding:8px 12px;background-color:{{accent}};font-size:13px;color:#ffffff;text-align:center;">{{caption}}</section>{{/caption}}</section>'),
  B('imageCard', 'i-cap-tint', '浅底图注', '<section style="margin:18px 0;"><img src="{{src}}" style="display:block;width:100%;max-width:100%;">{{#caption}}<section style="padding:8px 12px;background-color:{{tint}};font-size:13px;color:{{shade}};text-align:center;">{{caption}}</section>{{/caption}}</section>'),
  B('imageCard', 'i-underline', '下划线图', '<section style="margin:18px 0;text-align:center;"><img src="{{src}}" style="display:inline-block;width:100%;max-width:100%;"><section style="width:40px;height:3px;border-radius:99px;background-color:{{accent}};margin:9px auto 0;"></section>{{#caption}}<section style="margin-top:8px;font-size:13px;color:{{shade}};">{{caption}}</section>{{/caption}}</section>'),
];
